### ISSUE TITLE
formatting

### ISSUE THREAD

**Issue by hnstr** [Tristanhx/ARealChessGame#1]
De formatting van je README is niet helemaal goed gegaan! Check: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet als je twijfelt.
+ maak de plaatjes wat kleiner zodat de verhouding tekst/afbeelding wat prettiger leest

**Comment by Tristanhx** [comment]
Ik lees het nu pas. Gelijk gefixed.
